### ISSUE TITLE
Use in Silex

### ISSUE THREAD

**Issue by thegeekrv** [nibsirahsieu/SalvaJshrinkBundle#14]
Hello !

I'm having trouble to use this Bundle in Silex.
Is this possible ? How can it be done ?

Thx :)

**Comment by EmanueleMinotto** [comment]
Hello @thegeekrv, currently isn't possible because the bundle source code is mainly focused on Symfony 2, anyway this is a really good idea :+1: 

I'll work on it in the next days in a separate repository.

**Comment by thegeekrv** [comment]
Hell !

Thank's for your quick answer :)
Could you please let me know when it's ready?

**Comment by EmanueleMinotto** [comment]
Sure, I'll reply into this issue linking to the repo (and mentioning you). :)

**Comment by thegeekrv** [comment]
Cool :) Thank you :)

**Comment by thegeekrv** [comment]
For users interestes in a workaround, I've done this : 

```php
$app->after(function (Request $request, Response $response, Application $app) {
    $output = $response->getContent();

    $output = preg_replace_callback('/(?:<script\b[^>]*>)([\s\S]*?)(?:<\/script>)/im',
        function($matches) use($app){
            $fulltag = $matches[0];
            $jsInside = $matches[1];

            $nudeTag = str_replace($jsInside, "##JS-TMP-HERE##", $fulltag);

            $out = str_replace("##JS-TMP-HERE##", \JShrink\Minifier::minify($jsInside), $nudeTag);
            return $out;
        },
        $output);

    $response->setContent($output);

});
```

I know it's not the best, but it would be enough to start :)

**Comment by EmanueleMinotto** [comment]
@thegeekrv still a work in progress but already working: https://github.com/EmanueleMinotto/JshrinkServiceProvider
no release yet, so feedbacks are welcome :)

I'm closing this issue because it's not related to the SF2 bundle.
