### ISSUE TITLE
Symfony3 compatibility 

### ISSUE THREAD

**Issue by pesseyjulien** [nibsirahsieu/SalvaJshrinkBundle#19]
Hi,

Is the compatibility for Symfony 3 planned ?

Thanks,
Julien

**Comment by EmanueleMinotto** [comment]
Hi @pesseyjulien,
yes, I just need some spare time,
anyway if you want to send a PR it would be great!

**Comment by pesseyjulien** [comment]
Thanks for your answer. 
I could try to help but there is actually no deprecated calls logged in the profiler. 
Composer just throws an error when trying to update to SF3. It seems like the requirements for the bundle are not met by SF3. Anyway, not sure where to look :)

**Comment by EmanueleMinotto** [comment]
@pesseyjulien updated the dependencies allowing PHP7 too.
I'm closing this issue, reopen it if there's something wrong,
thanks :)

**Comment by pesseyjulien** [comment]
Great, thanks Emanuele ! :)
