### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by EmanueleMinotto** [nibsirahsieu/SalvaJshrinkBundle#4]
Isn't it ready for a 1.0.0 release/tag?

This could be helpful when inside the composer.json file there isn't a [minimum-stability](https://getcomposer.org/doc/04-schema.md#minimum-stability) flag (or it's setted to `stable`) and the developer install this bundle using `composer require`.

**Comment by nibsirahsieu** [comment]
i've just released v1.0.0. Thanks for reminder.

**Comment by EmanueleMinotto** [comment]
Thank you :)
