### ISSUE TITLE
No shrinkage in debug mode

### ISSUE THREAD

**Issue by artursvonda** [nibsirahsieu/SalvaJshrinkBundle#6]
Having `enable: %kernel.debug%` in config would be nice to disable jshrink in debug mode.

**Comment by EmanueleMinotto** [comment]
If you mean in Assetic you can disable it just prepending a `?` to the `jshrink` filter ([ref](http://symfony.com/doc/current/cookbook/assetic/yuicompressor.html#disable-minification-in-debug-mode)).
Or do you mean in the Twig extension too?

**Comment by artursvonda** [comment]
I mean extension should take that into account too.

**Comment by artursvonda** [comment]
Thanks for merging this! Will you, please, bump version?

**Comment by EmanueleMinotto** [comment]
Sure, I'll wait 1 or 2 days to receive some feedbacks but after these imo a `v1.1.0` can be released.

**Comment by EmanueleMinotto** [comment]
Done, thank you for the PR :)
