### ISSUE TITLE
Unusable because of performance issue 

### ISSUE THREAD

**Issue by robertfausk** [nibsirahsieu/SalvaJshrinkBundle#9]
@nibsirahsieu  @EmanueleMinotto 
When will https://github.com/nibsirahsieu/SalvaJshrinkBundle/pull/8 be merged?
I'm very interested in using your bundle but the performance impact is to big.
Using the new feature from @artursvonda solves this problem.

**Comment by EmanueleMinotto** [comment]
Hi @robertfausk, sorry but I missed the notification on 9 Mar.
Just replied on the PR, we'll continue there.
Thanks for the notifications. :)

**Comment by robertfausk** [comment]
No problem. You're welcome ;)
